# Generated by Django 5.2.13 on 2026-05-02 15:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2)),
                ('nome', models.CharField(max_length=200)),
                ('apelido', models.CharField(blank=True, max_length=200)),
                ('cpf_cnpj', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$|^\\d{14}$', 'Informe 11 dígitos (CPF) ou 14 dígitos (CNPJ).')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=300, verbose_name='endereço')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'pessoa',
                'verbose_name_plural': '.pessoas (PFs e PJs)',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PerfilProprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='perfil_proprietario', to='pessoas.pessoa')),
            ],
            options={
                'verbose_name': 'perfil proprietário',
                'verbose_name_plural': 'perfis proprietários',
            },
        ),
        migrations.CreateModel(
            name='PerfilImobiliaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creci', models.CharField(blank=True, max_length=30, verbose_name='CRECI')),
                ('contato_responsavel', models.CharField(blank=True, max_length=200, verbose_name='contato responsável')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='perfil_imobiliaria', to='pessoas.pessoa')),
            ],
            options={
                'verbose_name': 'perfil imobiliária',
                'verbose_name_plural': 'perfis imobiliárias',
            },
        ),
        migrations.CreateModel(
            name='PerfilFiador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profissao', models.CharField(blank=True, max_length=100, verbose_name='profissão')),
                ('renda_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='perfil_fiador', to='pessoas.pessoa')),
            ],
            options={
                'verbose_name': 'perfil fiador',
                'verbose_name_plural': 'perfis fiadores',
            },
        ),
        migrations.CreateModel(
            name='PerfilCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profissao', models.CharField(blank=True, max_length=100, verbose_name='profissão')),
                ('renda_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='perfil_cliente', to='pessoas.pessoa')),
            ],
            options={
                'verbose_name': 'perfil cliente (inquilino)',
                'verbose_name_plural': 'perfis clientes (inquilinos)',
            },
        ),
    ]
