# Generated by Django 5.2.13 on 2026-05-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilproprietario',
            name='interno',
            field=models.BooleanField(default=False, help_text='Marque se este proprietário faz parte da família/holding.'),
        ),
    ]
