# Generated by Django 5.2.13 on 2026-05-02 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_perfilproprietario_interno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$|^\\d{14}$', 'Informe 11 dígitos (CPF) ou 14 dígitos (CNPJ).')]),
        ),
    ]
