# Generated by Django 5.2.13 on 2026-07-07 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_alter_pessoa_cpf_cnpj'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'ordering': ['nome'], 'verbose_name': 'pessoa', 'verbose_name_plural': 'Pessoas (PFs e PJs)'},
        ),
    ]
