# Generated by Django 5.2.13 on 2026-05-02 22:16

import django.db.models.deletion
import documentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=documentos.models._documento_upload_path)),
                ('tipo', models.CharField(choices=[('MA', 'Matrícula'), ('ES', 'Escritura'), ('CO', 'Contrato'), ('AD', 'Aditivo Contratual'), ('CP', 'Comprovante de Pagamento'), ('SE', 'Seguro'), ('PR', 'Procuração'), ('IP', 'IPTU'), ('LI', 'Licença / Alvará'), ('ID', 'Documento de Identidade'), ('CR', 'Comprovante de Renda'), ('CC', 'Consulta de Score de Crédito'), ('OU', 'Outro')], max_length=2)),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='descrição')),
                ('vencimento', models.DateField(blank=True, help_text='Preencher para documentos com prazo (seguro, procuração, licença).', null=True)),
                ('metadados', models.JSONField(blank=True, default=dict, help_text='Campos extras específicos do tipo. Ex: {"numero_apolice": "...", "seguradora": "..."}')),
                ('object_id', models.PositiveIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='documentos__content_fe825b_idx')],
            },
        ),
    ]
