# Generated by Django 5.2.13 on 2026-05-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('MA', 'Matrícula'), ('ES', 'Escritura'), ('CO', 'Contrato'), ('AD', 'Aditivo Contratual'), ('CP', 'Comprovante de Pagamento'), ('SE', 'Seguro'), ('PR', 'Procuração'), ('IP', 'IPTU'), ('LI', 'Licença / Alvará'), ('ID', 'Documento de Identidade'), ('CR', 'Comprovante de Renda'), ('CC', 'Consulta de Score de Crédito'), ('CM', 'Município - CND'), ('FC', 'Município - Ficha Cadastral'), ('EP', 'Cartório - Escritura Pública'), ('CE', 'Cartório - Certidão de Registro'), ('CI', 'Cartório - Certidão de Inteiro Teor'), ('OU', 'Outro')], max_length=2),
        ),
    ]
