# Generated by Django 5.2.13 on 2026-05-02 16:45

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0002_perfilproprietario_interno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome de referência interno (ex: "Apto Centro")', max_length=200)),
                ('tipo', models.CharField(choices=[('AP', 'Apartamento'), ('CA', 'Casa'), ('SC', 'Sala Comercial'), ('IC', 'Imóvel Comercial'), ('GA', 'Galpão'), ('TE', 'Terreno'), ('OU', 'Outro')], max_length=2)),
                ('status', models.CharField(choices=[('DI', 'Disponível'), ('AL', 'Alugado'), ('VE', 'À Venda'), ('RE', 'Em Reforma'), ('IN', 'Inativo')], default='DI', max_length=2)),
                ('endereco', models.CharField(max_length=300, verbose_name='endereço')),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('area_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='área total (m²)')),
                ('quartos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vagas', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='vagas de garagem')),
                ('valor_mercado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='valor de mercado (R$)')),
                ('matricula', models.CharField(blank=True, max_length=50, verbose_name='matrícula do imóvel')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'imóvel',
                'verbose_name_plural': '.imóveis',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalImovel',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome de referência interno (ex: "Apto Centro")', max_length=200)),
                ('tipo', models.CharField(choices=[('AP', 'Apartamento'), ('CA', 'Casa'), ('SC', 'Sala Comercial'), ('IC', 'Imóvel Comercial'), ('GA', 'Galpão'), ('TE', 'Terreno'), ('OU', 'Outro')], max_length=2)),
                ('status', models.CharField(choices=[('DI', 'Disponível'), ('AL', 'Alugado'), ('VE', 'À Venda'), ('RE', 'Em Reforma'), ('IN', 'Inativo')], default='DI', max_length=2)),
                ('endereco', models.CharField(max_length=300, verbose_name='endereço')),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('area_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='área total (m²)')),
                ('quartos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vagas', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='vagas de garagem')),
                ('valor_mercado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='valor de mercado (R$)')),
                ('matricula', models.CharField(blank=True, max_length=50, verbose_name='matrícula do imóvel')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical imóvel',
                'verbose_name_plural': 'historical .imóveis',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ImovelProprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participacao', models.DecimalField(decimal_places=4, help_text='Ex: 0.5000 = 50%. A soma de todos os proprietários deve ser 1.', max_digits=5, verbose_name='participação (%)')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imoveis.imovel')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoas.perfilproprietario')),
            ],
            options={
                'verbose_name': 'proprietário do imóvel',
                'verbose_name_plural': 'proprietários do imóvel',
                'unique_together': {('imovel', 'proprietario')},
            },
        ),
    ]
