# Generated by Django 5.2.13 on 2026-05-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalimovel',
            name='endereco',
            field=models.CharField(blank=True, max_length=300, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='endereco',
            field=models.CharField(blank=True, max_length=300, verbose_name='endereço'),
        ),
    ]
