# Generated by Django 5.2.13 on 2026-05-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_alter_historicalimovel_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalimovel',
            name='status',
            field=models.CharField(choices=[('DI', 'Disponível'), ('AL', 'Alugado'), ('VE', 'À Venda'), ('RE', 'Em Reforma'), ('IN', 'Inativo'), ('GT', 'Gerido por terceiros')], default='DI', max_length=2),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='status',
            field=models.CharField(choices=[('DI', 'Disponível'), ('AL', 'Alugado'), ('VE', 'À Venda'), ('RE', 'Em Reforma'), ('IN', 'Inativo'), ('GT', 'Gerido por terceiros')], default='DI', max_length=2),
        ),
    ]
