# Generated by Django 5.2.13 on 2026-05-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_alter_historicalimovel_status_alter_imovel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalimovel',
            name='quartos',
        ),
        migrations.RemoveField(
            model_name='historicalimovel',
            name='vagas',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='quartos',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='vagas',
        ),
        migrations.AddField(
            model_name='historicalimovel',
            name='caracteristicas',
            field=models.JSONField(blank=True, default=dict, help_text='Campos específicos do tipo de imóvel.'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='caracteristicas',
            field=models.JSONField(blank=True, default=dict, help_text='Campos específicos do tipo de imóvel.'),
        ),
    ]
