# Generated by Django 5.2.13 on 2026-05-03 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0004_remove_historicalimovel_quartos_and_more'),
        ('pessoas', '0003_alter_pessoa_cpf_cnpj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalimovel',
            name='area_total',
        ),
        migrations.RemoveField(
            model_name='historicalimovel',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='area_total',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='matricula',
        ),
        migrations.AddField(
            model_name='historicalimovel',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='área (m²)'),
        ),
        migrations.AddField(
            model_name='historicalimovel',
            name='inscricao_municipal',
            field=models.CharField(blank=True, max_length=50, verbose_name='Inscrição Municipal'),
        ),
        migrations.AddField(
            model_name='historicalimovel',
            name='matricula_cartorio',
            field=models.CharField(blank=True, max_length=50, verbose_name='Matrícula do imóvel no cartorio'),
        ),
        migrations.AddField(
            model_name='historicalimovel',
            name='matricula_municipio',
            field=models.CharField(blank=True, max_length=50, verbose_name='Matrícula do imóvel na prefeitura'),
        ),
        migrations.AddField(
            model_name='historicalimovel',
            name='titular_registro',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Pessoa em cujo nome a matrícula está lavrada no cartório.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pessoas.pessoa', verbose_name='titular do registro'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='área (m²)'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='inscricao_municipal',
            field=models.CharField(blank=True, max_length=50, verbose_name='Inscrição Municipal'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='matricula_cartorio',
            field=models.CharField(blank=True, max_length=50, verbose_name='Matrícula do imóvel no cartorio'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='matricula_municipio',
            field=models.CharField(blank=True, max_length=50, verbose_name='Matrícula do imóvel na prefeitura'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='titular_registro',
            field=models.ForeignKey(blank=True, help_text='Pessoa em cujo nome a matrícula está lavrada no cartório.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imoveis_como_titular', to='pessoas.pessoa', verbose_name='titular do registro'),
        ),
    ]
