# Generated by Django 5.2.13 on 2026-05-06 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0005_remove_historicalimovel_area_total_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalimovel',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical imóvel', 'verbose_name_plural': 'historical Imóveis'},
        ),
        migrations.AlterModelOptions(
            name='imovel',
            options={'ordering': ['nome'], 'verbose_name': 'imóvel', 'verbose_name_plural': 'Imóveis'},
        ),
        migrations.RenameField(
            model_name='historicalimovel',
            old_name='cidade',
            new_name='municipio',
        ),
        migrations.RenameField(
            model_name='imovel',
            old_name='cidade',
            new_name='municipio',
        ),
    ]
