# Generated by Django 5.2.13 on 2026-07-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0006_alter_historicalimovel_options_alter_imovel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalimovel',
            name='status',
            field=models.CharField(choices=[('DI', 'Disponível'), ('AL', 'Alugado'), ('VE', 'À Venda'), ('RE', 'Em Reforma'), ('IN', 'Inativo'), ('GT', 'Gerido por terceiros'), ('VD', 'Vendido')], default='DI', max_length=2),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='status',
            field=models.CharField(choices=[('DI', 'Disponível'), ('AL', 'Alugado'), ('VE', 'À Venda'), ('RE', 'Em Reforma'), ('IN', 'Inativo'), ('GT', 'Gerido por terceiros'), ('VD', 'Vendido')], default='DI', max_length=2),
        ),
    ]
