# Generated by Django 5.2.13 on 2026-05-02 19:43

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imoveis', '0003_alter_historicalimovel_status_alter_imovel_status'),
        ('pessoas', '0003_alter_pessoa_cpf_cnpj'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='data de início')),
                ('vigencia', models.IntegerField(verbose_name='Vigência em meses')),
                ('renovacao_automatica', models.BooleanField(default=False, verbose_name='Renovação automatica?')),
                ('quant_renov_automaticas', models.PositiveSmallIntegerField(default=0, verbose_name='Quantidade de renovações automáticas permitidas')),
                ('valor_aluguel', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor do aluguel (R$)')),
                ('indice_reajuste', models.CharField(choices=[('IGPM', 'IGP-M'), ('IPCA', 'IPCA'), ('INCC', 'INCC'), ('FIXO', 'Fixo (sem reajuste)'), ('OUTRO', 'Outro índice')], default='IGPM', max_length=5, verbose_name='índice de reajuste')),
                ('dia_vencimento', models.PositiveSmallIntegerField(help_text='Dia do mês em que o aluguel vence (1–28).', verbose_name='dia de vencimento')),
                ('rescindido_em', models.DateField(blank=True, null=True, verbose_name='rescindido em')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='pessoas.perfilcliente')),
                ('imobiliaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='pessoas.perfilimobiliaria')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='imoveis.imovel')),
            ],
            options={
                'verbose_name': 'contrato',
                'verbose_name_plural': '.contratos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FI', 'Fiador'), ('DE', 'Depósito Caução'), ('SE', 'Seguro'), ('SG', 'Contrato sem Garantias')], max_length=2)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, help_text='Valor do depósito, prêmio do seguro ou título de capitalização.', max_digits=12, null=True, verbose_name='valor (R$)')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garantias', to='contratos.contrato')),
                ('fiador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='garantias', to='pessoas.perfilfiador')),
            ],
            options={
                'verbose_name': 'garantia',
                'verbose_name_plural': 'garantias',
            },
        ),
        migrations.CreateModel(
            name='HistoricalContrato',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='data de início')),
                ('vigencia', models.IntegerField(verbose_name='Vigência em meses')),
                ('renovacao_automatica', models.BooleanField(default=False, verbose_name='Renovação automatica?')),
                ('quant_renov_automaticas', models.PositiveSmallIntegerField(default=0, verbose_name='Quantidade de renovações automáticas permitidas')),
                ('valor_aluguel', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor do aluguel (R$)')),
                ('indice_reajuste', models.CharField(choices=[('IGPM', 'IGP-M'), ('IPCA', 'IPCA'), ('INCC', 'INCC'), ('FIXO', 'Fixo (sem reajuste)'), ('OUTRO', 'Outro índice')], default='IGPM', max_length=5, verbose_name='índice de reajuste')),
                ('dia_vencimento', models.PositiveSmallIntegerField(help_text='Dia do mês em que o aluguel vence (1–28).', verbose_name='dia de vencimento')),
                ('rescindido_em', models.DateField(blank=True, null=True, verbose_name='rescindido em')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pessoas.perfilcliente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('imobiliaria', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pessoas.perfilimobiliaria')),
                ('imovel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='imoveis.imovel')),
            ],
            options={
                'verbose_name': 'historical contrato',
                'verbose_name_plural': 'historical .contratos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
